version: "3.4"
services:
    postgres:
        image: postgres:latest
        command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c max_connections=10000
        ports:
            - "5432:5432"
        env_file:
            - ./env_files/postgres.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            autopsy_net:
                aliases:
                    - postgres
        restart: unless-stopped

    solr:
        build:
            context: include/solr4
            args:
                - SOLR_UID=$BUILD_UID
                - SOLR_GID=$BUILD_GID
                - AUTOPSY_VERSION=$AUTOPSY_VERSION
        ports:
            - "8983:8983"
            - "9983:9983"
        volumes:
            - solr_data:/opt/solr
            # this is needed according to the Autopsy documentation
            - autopsy_cases:/cases
        networks:
            autopsy_net:
                aliases:
                    - solr
        restart: unless-stopped

    activemq:
        image: rmohr/activemq:latest
        ports:
            - "61616:61616"
        volumes:
            - activemq_data:/mnt/data
        networks:
            autopsy_net:
                aliases:
                    - activemq
        restart: unless-stopped

    autopsy-server:
        depends_on:
            - postgres
            - solr
            - activemq
        build:
            context: .
            args:
                - AUTOPSY_VERSION=$AUTOPSY_VERSION
                - SLEUTHKIT_VERSION=$SLEUTHKIT_VERSION
                - AUTOPSY_UID=$BUILD_UID
                - AUTOPSY_GID=$BUILD_GID
        ports:
            - "5911:5901"
        volumes:
            - autopsy_config:/config
            - autopsy_cases:/cases
            - autopsy_images:/images
        networks:
            autopsy_net:
                aliases:
                    - autopsy-server
        restart: always

networks:
    autopsy_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.1.0/24



volumes:
    postgres_data: {}
    solr_data: {}
    activemq_data: {}
    autopsy_config: {}
    autopsy_cases: {}
    autopsy_images: {}
